"use agnostic";

import { usernameRegExp } from "~/better-auth/constants/agnostic/regexes";

/**
 * $COMMENT#JSDOC#UTILS#DEFS#VALIDATEUSERNAMESLUGFRIENDLY
 * - $COMMENT#JSDOC#UTILS#DETAILS#STARTSALPHANUMERICAL
 * - $COMMENT#JSDOC#UTILS#DETAILS#NEITHERDOUBLEHYPHENSUNDERSCORES
 * - $COMMENT#JSDOC#UTILS#DETAILS#HYPHENSUNDERSCORESMIDDLE
 * - and $COMMENT#JSDOC#UTILS#DETAILS#ENDSSALPHANUMERICAL
 * @param username $COMMENT#JSDOC#UTILS#PARAMS#USERNAME
 * @returns $COMMENT#JSDOC#UTILS#RETURNS#VALIDATEUSERNAMESLUGFRIENDLY
 */
export const validateUsernameSlugFriendly = (username: string) =>
  usernameRegExp.test(username);
